version: "3.1"

services:
  nginx:
    image: nginx
    container_name: enviame_nginx
    depends_on:
      - api
      - db
    volumes:
      - "${VOLUME_NGINX}:/etc/nginx/config.d"
    ports:
      - "${NGINX_PORT}:80"
    links:
      - "api:api"
      - "db:db"
  

  api:
    container_name: enviame_api
    image: enviame_api:latest
    build:
      context: ${VOLUME_API}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "${VOLUME_API}:/app"
    depends_on:    
      - db
    
  db:
    image: mysql
    container_name: enviame_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./scripts/init_database.sql:/docker-entrypoint-initdb.d/init.sql"
      - "db-mysql-volume:/var/lib/mysql"      

    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
  
volumes:
  db-mysql-volume: